name: a1_sim
urdf_path: src/simulation/robots/a1_description/urdf/a1.urdf
robot_params:
  total_mass: 13
  total_inertia: [ 0.24, 0, 0, 0, 0.80, 0, 0, 0, 1.0 ] 
  body_mass: 6
  body_size: [0.267, 0.194, 0.114]
  body_inertia: [0.015853, 0, 0, 0, 0.037799, 0, 0, 0, 0.045654 ]
  links_inertia: [[0.000469246, -9.409e-06, -3.42e-07,-9.409e-06, 0.00080749,-4.66e-07,-3.42e-07, -4.66e-07, 0.000552929],
                  [0.005529065, 4.825e-06, 0.000343869, 4.825e-06, 0.005139339, 2.2448e-05, 0.000343869, 2.2448e-05, 0.001367788],
                  [0.002997972, 0.0,-0.000141163, 0.0, 0.003014022, 0.0, -0.000141163, 0.0, 3.2426e-05]] # for one leg
  links_mass: [0.696, 1.013, 0.166] # for one leg
  links_com_pos: [[-0.0033, 0, 0], [-0.003237, -0.022327, -0.027326], [0.006435, 0, -0.107]] # for FL leg
  body_height: 0.28
  abad_location: [0.1805, 0.047, 0]
  hip_l: 0.08505
  upper_l: 0.2
  lower_l: 0.2

  velocity:
    # com_offset: [ -0.005, 0.0022, 0.000515 ] # zang mpc
    com_offset: [ 0.005, 0.00145, 0.000515 ] # vel mode
  position:
    com_offset: [ -0.005, 0.0024, 0.000515 ] # pos mode
  walk:
    com_offset: [ -0.005, 0.0012, 0.000515 ] # walk mode
    # com_offset: [ -0.01, 0.003, 0.000515 ] # mpc/walk
  advanced_trot:
    # com_offset: [ -0.004, 0.00145, 0.000515 ] # vel mode
    # com_offset: [ 0.0, 0.00195, 0.000515 ] # yh-mpc
    com_offset: [ -0.008, 0.005, 0. ] # only for test
  hip_offset: [ [ 0.1805, -0.047, 0. ],
                [ 0.1805, 0.047, 0. ],
                [ -0.1805, -0.047, 0. ],
                [ -0.1805, 0.047, 0. ] ]
  # default_hip_positions: [ [ 0.17, -0.135, 0 ],
  #                          [ 0.17, 0.135, 0 ],
  #                          [ -0.195, -0.135, 0 ],
  #                          [ -0.195, 0.135, 0 ] ]
  default_hip_positions: [ [ 0.185, -0.135, 0 ],
                           [ 0.185, 0.135, 0 ],
                           [ -0.185, -0.135, 0 ],
                           [ -0.185, 0.135, 0 ] ]
  
  default_standup_angle:
    ab: 0
    hip: 0.9
    knee: -1.8

  default_sitdown_angle:
    ab: -0.167136
    hip: 0.934969
    knee: -2.54468

motor_params:
  kps: [ 100,100,100 ]
  kds: [ 1.0,1.0,1.0 ]
  joint_directions: [ 1,1,1, 1,1,1, 1,1,1, 1,1,1 ]
  joint_offsets: [ 0,0,0, 0,0,0, 0,0,0, 0,0,0 ]
  stand_angle: [ 0,0.67,-1.25 ]

  abad_p: 100.0
  abad_d: 1.0
  hip_p: 100.0
  hip_d: 2.0
  knee_p: 100.0
  knee_d: 2.0

controller_params:
  # mode: 0 # VEL_MODE
  # mode: 1 # POS_MODE
  # mode: 2 # WALK_LOCOMOTION
  mode: 3 # ADVANCED_TROT

# is simulate or not
is_sim: true
