name: a1_sim
gait_params:
  gaitName: "trot"
  trot:
    stance_duration: [ 0.3, 0.3, 0.3, 0.3 ]
    duty_factor: [ 0.6, 0.6, 0.6, 0.6 ]
    init_phase_full_cycle: [ 0.9, 0., 0., 0.9 ]
    initial_leg_state: [ 0, 1, 1, 0 ]  # STANCE: 1, SWING: 0
    contact_detection_phase_threshold: 0.1
  stand:
    stance_duration: [ 0.3, 0.3, 0.3, 0.3 ]
    duty_factor: [ 1., 1, 1., 1. ]
    init_phase_full_cycle: [ 0., 0., 0., 0. ]
    initial_leg_state: [ 1, 1, 1, 1 ]  # STANCE: 1, SWING: 0
    contact_detection_phase_threshold: 0.1
  threestand:
    stance_duration: [ 0.3, 0.3, 0, 0.3 ]
    duty_factor: [ 1., 1., 0, 1 ]
    init_phase_full_cycle: [ 0., 0., 0., 0. ]
    initial_leg_state: [ 1, 1, 0, 1 ]  # STANCE: 1, SWING: 0
    contact_detection_phase_threshold: 0.1