name: robot_go1
robot_params:
  body_mass: 10
  body_inertia: [ 0.24, 0, 0, 0, 0.80, 0, 0, 0, 1.0 ]
  body_height: 0.295
  hip_l: 0.08505
  upper_l: 0.213
  lower_l: 0.213

  # x++ back++     y++ right++
  com_offset: [ -0.038, -0.005, 0.0005 ] # for GO1
  hip_offset: [ [ 0.17, -0.055, 0. ],
                [ 0.17, 0.055, 0. ],
                [ -0.21, -0.055, 0. ],
                [ -0.21, 0.055, 0. ] ]
  default_hip_positions: [ [ 0.20, -0.14, 0 ],
                           [ 0.20, 0.14, 0 ],
                           [ -0.18, -0.14, 0 ],
                           [ -0.18, 0.14, 0 ] ]
  default_standup_angle:
    ab: 0
    hip: 0.8
    knee: -1.6
   
  default_sitdown_angle:
    ab: -0.167136
    hip: 0.934969
    knee: -2.54468

motor_params:
  # kps: [ 100,100,100 ]
  # kds: [ 1.0,2.0,2.0 ]
  joint_directions: [ 1,1,1, 1,1,1, 1,1,1, 1,1,1 ]
  joint_offsets: [ 0,0,0, 0,0,0, 0,0,0, 0,0,0 ]
  stand_angle: [ 0,0.67,-1.25 ]

  abad_p: 100.0
  abad_d: 1.0 # 1
  hip_p: 100.0
  hip_d: 2.0 # 2
  knee_p: 100.0
  knee_d: 2.0 # 2

contorller_params:
  mode: 0 # VEL_MODE
  # mode: 1 # POS_MODE