name: robot_go1
stance_leg_params:
    force_dim: 3
    # KP:  [300., 300., 100., 200., 200., 200.]
    KP:  [300., 300., 100., 200., 200., 0.]
    # KD:  [40., 30., 10., 10., 10., 30.] # for vel mode
    KD:  [10., 10., 10., 10., 10., 10.] # for pos mode
    
    max_ddq: [10., 10., 10., 20., 20., 20.]
    min_ddq: [-10., -10., -10., -20., -20., -20.]
    acc_weight: [1., 1., 1., 10., 10., 1.]

