name: a1_sim
stance_leg_params:
    force_dim: 3
    velocity:
        KP:  [100., 100., 100., 200., 200., 0] # robot_com_position, robot_com_roll_pitch_yaw
        KD:  [20., 20., 10., 20., 20., 25.] # robot_com_velocity, robot_com_roll_pitch_yaw_rate
        max_ddq: [10., 10., 10., 20., 20., 20.]
        min_ddq: [-10., -10., -10., -20., -20., -20.]        
        acc_weight: [1., 1., 1., 10., 10., 1.]
        X_weight: [20., 15., 15., 20., 20., 50., 1., 1., 1., 1., 1., 1., 50.]     
    position:
        # for pos mode
        KP:  [100., 200., 200., 100., 100., 200.] # robot_com_position, robot_com_roll_pitch_yaw
        KD:  [20., 20., 10., 20., 20., 25.] # robot_com_velocity, robot_com_roll_pitch_yaw_rate
        max_ddq: [10., 10., 10., 20., 20., 20.]
        min_ddq: [-10., -10., -10., -20., -20., -20.]        
        # acc_weight: [1., 1., 1., 1., 1., 1.]
        acc_weight: [1., 1., 1., 10., 10., 1.]
        #         roll,pitch,yaw, x,  y,   z,  droll,dpitch,dyaw,dx,dy,dz   
        X_weight: [20., 15., 15., 20., 20., 50., 1., 1., 1., 1., 1., 1., 50.]   
    walk:
        KP:  [100., 200., 100., 100., 100., 200.] # robot_com_position, robot_com_roll_pitch_yaw
        KD:  [40., 30., 10., 10., 10., 30.] # robot_com_velocity, robot_com_roll_pitch_yaw_rate
        max_ddq: [10., 10., 10., 20., 20., 20.]
        min_ddq: [-10., -10., -10., -20., -20., -20.]        
        acc_weight: [1., 1., 1., 10., 10., 1.]
        X_weight: [20., 15., 15., 20., 20., 50., 1., 1., 1., 1., 1., 1., 50.]  
