name: aliengo
urdf_path: src/simulation/robots/aliengo_description/xacro/aliengo.urdf
robot_params:
  total_mass: 25 # 4*(0.06 + 0.207 + 0.639+1.993) = 11.596 +9.041 = 20.63
  # total_inertia: [ 0.24, 0, 0, 0, 0.80, 0, 0, 0, 1.0 ]
  total_inertia: [ 0.4, 0, 0.1, 0, 1.15, 0, 0.1, 0, 1.03 ] # TODO
  
  body_mass: 13.041 # 9.041
  body_size: [0.647, 0.21, 0.13]
  # body_inertia: [0.033260, -0.0004516, 0.0004876, -0.0004516, 0.161172, 0.0000484, 0.0004876, 0.0000484, 0.174604]
  body_inertia: [0.3, -0, 0.1, 0, 0.1, 0, 0.1, 0, 1] # add arm
  # body_inertia: [0.24, -0, 0.1, 0, 0.5, 0, 0.1, 0, 0.31] # add arm
  
  links_inertia: [[0.002904, 7.185e-05, -1.262e-06,7.185e-05, 0.004908,1.75e-06,-1.262e-06, 1.75e-06, 0.005587],
                  [0.005667, 3.597e-06, 0.000491, 3.597e-06, 0.005847, 1.0086e-05, 0.000491, 1.0086e-05, 0.000370],
                  [0.006341, 0, -8.7951e-05, 0, 0.006355, -1.336e-06, -8.7951e-05, -1.336e-06, 3.9188e-05],
                  # [1.6854e-05, 0 , 0, 0, 1.6854e-05, 0, 0, 0, 1.6854e-05] foot
                  ] # for one left leg
  links_mass: [1.993, 0.639, 0.207] # for one leg
  links_com_pos: [[-0.0222, 0.0151, 0], [-0.005607, -0.003877, -0.048199], [0.002781, 0, -0.1425]] # for FL leg
                #-0.022191 -0.015144 -1.5e-05
                # -0.005607 0.003877 -0.048199
                # 0.002781 6.3e-05 -0.142518
  body_height: 0.37
  abad_location: [0.2399, 0.015, 0]
  hip_l: 0.083
  upper_l: 0.25
  lower_l: 0.25

  velocity:
    com_offset: [ -0.02, -0.015, 0.000515 ]  # y++: right++ x++: back++
    # com_offset: [ -0.0, -0.015, 0.000515 ]
  position:
    # com_offset: [ 0.005, 0.0028, 0.000515 ]
    com_offset: [ 0.005, -0.000, 0.000515 ]
  walk:
    com_offset: [ -0.01, 0.003, 0.000515 ] # mpc, walk mode
  advanced_trot:
    # com_offset: [ 0.0, 0.00195, 0.000515 ] # yh-mpc
    # com_offset: [ -0.01, 0., 0. ]
    com_offset: [ 0.02, -0.005, 0.03 ] # have a arm
  
  hip_offset: [ [ 0.2399, -0.051, 0. ],
                [ 0.2399, 0.051, 0. ],
                [ -0.2399, -0.051, 0. ],
                [ -0.2399, 0.051, 0. ] ]
  default_hip_positions: [ [ 0.24, -0.135, 0 ],
                           [ 0.24, 0.135, 0 ],
                           [ -0.25, -0.135, 0 ],
                           [ -0.25, 0.135, 0 ] ]
  # default_hip_positions: [ [ 0.24, -0.135, 0 ],
  #                          [ 0.24, 0.135, 0 ],
  #                          [ -0.24, -0.135, 0 ],
  #                          [ -0.24, 0.135, 0 ] ]
  
  default_standup_angle:
    ab: 0
    hip: 0.9
    knee: -1.8

  # default_sitdown_angle:
  #   ab: -0.167136
  #   hip: 0.934969
  #   knee: -2.54468
  
  default_sitdown_angle:
    ab: -0.
    hip: 1.2
    knee: -2.6

motor_params:
  kps: [ 100,100,100 ]
  kds: [ 1.0,1.0,1.0 ]
  joint_directions: [ 1,1,1, 1,1,1, 1,1,1, 1,1,1 ]
  joint_offsets: [ 0,0,0, 0,0,0, 0,0,0, 0,0,0 ]
  stand_angle: [ 0,0.67,-1.25 ]

  # abad_p: 140.0
  # abad_d: 1.0
  # hip_p: 150.0
  # hip_d: 2.0
  # knee_p: 150.0
  # knee_d: 2.0

  
  abad_p: 200.0
  abad_d: 3
  hip_p: 100.0
  hip_d: 2.0
  knee_p: 200.0
  knee_d: 2.0

controller_params:
  # mode: 0 # VEL_MODE
  # mode: 1 # POS_MODE
  # mode: 2 # WALK_LOCOMOTION
  mode: 3 # ADVANCED_TROT

is_sim: false
