name: aliengo
gait_params:
  gait: "advanced_trot"
  wait_time: 0.3
  trot:
    stance_duration: [ 0.3, 0.3, 0.3, 0.3 ]
    duty_factor: [ 0.6, 0.6, 0.6, 0.6 ]
    init_phase_full_cycle: [ 0.5, 0., 0., 0.5 ]
    initial_leg_state: [ 1, 1, 1, 1 ]
    contact_detection_phase_threshold: 0.5
  stand:
    stance_duration: [ 0.23, 0.23, 0.23, 0.23 ]
    duty_factor: [ 1., 1., 1., 1. ]
    init_phase_full_cycle: [ 0., 0., 0., 0. ]
    initial_leg_state: [ 1, 1, 1, 1 ]  # STANCE: 1, SWING: 0
    contact_detection_phase_threshold: 0.1
  walk:
    stance_duration: [ 7.5, 7.5, 7.5, 7.5 ]
    duty_factor: [ 0.75, 0.75, 0.75, 0.75 ]
    # init_phase_full_cycle: [ 0., 0.5, 0.25, 0.75 ] # RL
    init_phase_full_cycle: [ 0.5, 0., 0.75, 0.25 ] # RR 
    # init_phase_full_cycle: [ 0.25, 0.75, 0.5, 0. ] # FL
    # init_phase_full_cycle: [ 0.75, 0.25, 0., 0.5 ] # FR
    # init_phase_full_cycle: [ 0., 0.25, 0.5, 0.75 ] # anymal walk order
    initial_leg_state: [ 1, 1, 1, 1]  # STANCE: 1, SWING: 0
    contact_detection_phase_threshold: 0.1
    state_switch_que: ["full_stance", "unload_force", "true_swing", "load_force"] # processes in total swing phase for a leg
    state_ratio: [0.2, 0.3, 0.3, 0.2] # full_stance + unload/load force = stance duty_factor
    move_base_ratio_point: [0.75, 0.875]
  advanced_trot:
    # stance_duration: [ 0.5, 0.5, 0.5, 0.5 ]
    stance_duration: [ 0.55, 0.55, 0.55, 0.55 ]
    # stance_duration: [ 0.6, 0.6, 0.6, 0.6 ]
    # stance_duration: [ 0.7, 0.7, 0.7, 0.7 ]
    # duty_factor: [ 0.6, 0.6, 0.6, 0.6 ]
    duty_factor: [ 0.7, 0.7, 0.7, 0.7 ]
    init_phase_full_cycle: [ 0.5, 0., 0., 0.5 ]
    initial_leg_state: [ 1, 1, 1, 1 ]  # STANCE: 1, SWING: 0
    contact_detection_phase_threshold: 0.4